# Generated by Django 5.1.2 on 2025-02-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImageUpload',
        ),
    ]
